# Generated by Django 5.2.16 on 2026-07-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LlmProviderConfig',
            fields=[
                ('llm1_primary_provider', models.CharField(default='openai', max_length=20, verbose_name='LLM1 Provider primário')),
                ('llm1_primary_model', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='LLM1 Model primário')),
                ('llm1_primary_api_key', models.CharField(blank=True, max_length=255, verbose_name='LLM1 API Key primário')),
                ('llm1_primary_base_url', models.CharField(blank=True, max_length=255, verbose_name='LLM1 Base URL primário')),
                ('llm1_secondary_provider', models.CharField(default='openai', max_length=20, verbose_name='LLM1 Provider secundário')),
                ('llm1_secondary_model', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='LLM1 Model secundário')),
                ('llm1_secondary_api_key', models.CharField(blank=True, max_length=255, verbose_name='LLM1 API Key secundário')),
                ('llm1_secondary_base_url', models.CharField(blank=True, max_length=255, verbose_name='LLM1 Base URL secundário')),
                ('llm2_primary_provider', models.CharField(default='openai', max_length=20, verbose_name='LLM2 Provider primário')),
                ('llm2_primary_model', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='LLM2 Model primário')),
                ('llm2_primary_api_key', models.CharField(blank=True, max_length=255, verbose_name='LLM2 API Key primário')),
                ('llm2_primary_base_url', models.CharField(blank=True, max_length=255, verbose_name='LLM2 Base URL primário')),
                ('llm2_secondary_provider', models.CharField(default='openai', max_length=20, verbose_name='LLM2 Provider secundário')),
                ('llm2_secondary_model', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='LLM2 Model secundário')),
                ('llm2_secondary_api_key', models.CharField(blank=True, max_length=255, verbose_name='LLM2 API Key secundário')),
                ('llm2_secondary_base_url', models.CharField(blank=True, max_length=255, verbose_name='LLM2 Base URL secundário')),
                ('secondary_enabled', models.BooleanField(default=False, verbose_name='LLM secundário habilitado')),
                ('single_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Providers LLM',
                'verbose_name_plural': 'Configuração de Providers LLM',
            },
        ),
    ]
