# Generated by Django 5.2.13 on 2026-05-07 13:05

from django.db import migrations


def seed_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    roles = ["nurse", "doctor", "admin"]
    for name in roles:
        Role.objects.get_or_create(name=name)


def seed_admin_role_for_superusers(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    User = apps.get_model("accounts", "User")
    admin_role, _ = Role.objects.get_or_create(name="admin")
    for user in User.objects.filter(is_superuser=True):
        user.roles.add(admin_role)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_roles, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(seed_admin_role_for_superusers, reverse_code=migrations.RunPython.noop),
    ]
