# Generated by Django 5.2.16 on 2026-07-19 13:08

import apps.cases.models
import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('NEW', 'New'), ('EXTRACTING', 'Extracting'), ('LLM1_STRUCT', 'LLM1 Struct'), ('LLM2_SUGGEST', 'LLM2 Suggest'), ('WAIT_DOCTOR', 'Wait Doctor'), ('DOCTOR_ACCEPTED', 'Doctor Accepted'), ('DOCTOR_DENIED', 'Doctor Denied'), ('WAIT_NURSE_ACK', 'Wait Nurse Ack'), ('FAILED', 'Failed'), ('CLEANED', 'Cleaned')], default='NEW', max_length=30, protected=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True)),
                ('agency_record_number', models.CharField(blank=True, max_length=20)),
                ('regulation_days_on_screen', models.PositiveIntegerField(blank=True, null=True)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('llm1_primary_result', models.JSONField(blank=True, null=True)),
                ('llm1_secondary_result', models.JSONField(blank=True, null=True)),
                ('llm2_primary_result', models.JSONField(blank=True, null=True)),
                ('llm2_secondary_result', models.JSONField(blank=True, null=True)),
                ('suggested_action', models.JSONField(blank=True, null=True)),
                ('doctor_decision', models.CharField(blank=True, max_length=10)),
                ('doctor_reason', models.TextField(blank=True)),
                ('doctor_observation', models.CharField(blank=True, max_length=500)),
                ('doctor_decided_at', models.DateTimeField(blank=True, null=True)),
                ('nurse_ack_at', models.DateTimeField(blank=True, null=True)),
                ('admin_closed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_closure_reason_code', models.CharField(blank=True, max_length=40)),
                ('admin_closure_reason_text', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lock_token', models.UUIDField(blank=True, null=True)),
                ('lock_context', models.CharField(blank=True, max_length=40)),
                ('lock_role', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_admin_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_decided', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_locked', to=settings.AUTH_USER_MODEL)),
                ('nurse_ack_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_nurse_acknowledged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('attachment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.cases.models.case_attachment_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_suppressed', models.BooleanField(db_index=True, default=False)),
                ('suppressed_at', models.DateTimeField(blank=True, null=True)),
                ('suppression_reason', models.TextField(blank=True)),
                ('upload_phase', models.CharField(default='initial', max_length=20)),
                ('uploaded_when_case_status', models.CharField(blank=True, max_length=30)),
                ('note', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case')),
                ('suppressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_attachments_suppressed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseCommunicationMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_role', models.CharField(blank=True, max_length=30)),
                ('body', models.TextField()),
                ('message_type', models.CharField(default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_communication_messages', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_messages', to='cases.case')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(max_length=10)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'locked_until'], name='cases_case_status_9206d0_idx'),
        ),
        migrations.AddIndex(
            model_name='caseattachment',
            index=models.Index(fields=['case', 'created_at'], name='cases_casea_case_id_f4b8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='casecommunicationmessage',
            index=models.Index(fields=['case', 'created_at'], name='cases_casec_case_id_44d48d_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'timestamp'], name='cases_casee_case_id_012553_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='cases_casee_event_t_1245c7_idx'),
        ),
    ]
