# Generated by Django 5.2.16 on 2026-07-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='Nome do prompt')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('content', models.TextField(verbose_name='Conteúdo do prompt')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de Prompt',
                'verbose_name_plural': 'Templates de Prompt',
                'ordering': ['name', '-version'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
